;METADATA=(Diff=true, UseCommands=true)
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=FEA18B124B1784D9B8E59C9E114EA7B4

[/Script/UnrealEd.ProjectPackagingSettings]
+DirectoriesToAlwaysStageAsUFS=(Path="ArticyContent/Generated")
+DirectoriesToAlwaysCook=(Path="/Game/ArticyContent")

